namespace MonsterTrainAccessibility.Presentation.Verbosity
{
    internal enum PresentationSlot
    {
        Title,
        Subtitle,
        Cost,
        Stats,
        Description,
        Ability,
        Intent,
        DynamicInfo,
        Upgrade,
        Trigger,
        Status,
        Context,
        Tooltip,
        TooltipKeyword,
        TooltipStatus,
        TooltipTrigger,
        TooltipEffect,
        TooltipAbility,
        TooltipUpgrade,
        TooltipEquipment,
        TooltipRoomEffect,
        TooltipGeneratedContent,
        TooltipOther,
        NestedPresentation,
        Annotation
    }
}
